import './globals.css';
import type { Metadata } from 'next';
import { fontsVariables } from '@/lib';
import { Navigation } from '@/layouts';
import TanstackQueryProvider from '@/utils/TanstackQueryProvider';

export const metadata: Metadata = {
  title: 'Reqeefy',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={fontsVariables}>
        <TanstackQueryProvider>
          <Navigation />
          <main>{children}</main>
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
